import { NextRequest, NextResponse } from "next/server";
import { getPlan } from "@/lib/db/repo";
import { checkPlanOwnership } from "@/app/api/auth-utils";
import type { Plan } from "@/lib/types";

interface GitHubFile {
  path: string;
  content: string;
}

async function githubFetch(url: string, token: string, method = "GET", body?: unknown) {
  const res = await fetch(url, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      "Accept": "application/vnd.github+json",
      "Content-Type": "application/json",
      "User-Agent": "IdeForge",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const data = await res.json().catch(() => null);
  return { ok: res.ok, status: res.status, data };
}

function generateProjectFiles(plan: Plan): GitHubFile[] {
  const files: GitHubFile[] = [];
  const appName = plan.structure?.appName || "MyApp";
  const summary = plan.structure?.summary || "";

  const features = plan.structure?.features || [];
  const featureList = features.map((f) =>
    `- **${f.name}** (Fase ${f.phase}): ${f.subFeatures.map((s) => s.name).join(", ")}`
  ).join("\n");

  const tech = plan.techChoice
    ? `- Frontend: ${plan.techChoice.frontend}\n- Backend: ${plan.techChoice.backend}\n- Database: ${plan.techChoice.database}`
    : "- (belum dipilih)";

  const tasks = plan.tasks || [];
  const taskList = tasks
    .filter((t) => !t.done)
    .map((t) => `- [ ] ${t.title} _(Fase ${t.phase})_`)
    .join("\n");

  files.push({
    path: "README.md",
    content: `# ${appName}

${summary}

## Tech Stack
${tech}

## Getting Started
\`\`\`bash
# Clone repo
git clone https://github.com/YOUR_USERNAME/${appName.toLowerCase().replace(/\s+/g, "-")}.git
cd ${appName.toLowerCase().replace(/\s+/g, "-")}

# Install dependencies
# TODO: add install commands based on your tech stack
\`\`\`

## Features
${featureList}

## Tasks Remaining
${taskList || "- No remaining tasks"}

---
*Generated by [IdeForge](https://ideforge.app)*
`,
  });

  if (plan.prd) {
    files.push({
      path: "PRD.md",
      content: plan.prd,
    });
  }

  if (plan.srs) {
    files.push({
      path: "SRS.md",
      content: plan.srs,
    });
  }

  files.push({
    path: "docs/tech-stack.md",
    content: `# Tech Stack\n\n## Frontend\n${plan.techChoice?.frontend || "-"}\n\n## Backend\n${plan.techChoice?.backend || "-"}\n\n## Database\n${plan.techChoice?.database || "-"}\n\n${plan.techChoice?.reasoning ? `## Reasoning\n${plan.techChoice.reasoning}` : ""}`,
  });

  files.push({
    path: "docs/features.md",
    content: `# Feature Structure\n\n${features.map((f) =>
      `## ${f.name} (Fase ${f.phase})\n${f.subFeatures.map((s) => `- ${s.name}`).join("\n")}`
    ).join("\n\n")}`,
  });

  if (plan.finalPrompt) {
    files.push({
      path: "docs/prompt.md",
      content: plan.finalPrompt,
    });
  }

  return files;
}

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const plan = await getPlan(id);
  if (!plan) {
    return NextResponse.json({ error: "Plan tidak ditemukan." }, { status: 404 });
  }

  const ownershipError = await checkPlanOwnership(plan);
  if (ownershipError) return ownershipError;

  let body: { token?: string; repo?: string; description?: string; private?: boolean };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Body request tidak valid." }, { status: 400 });
  }

  const { token, repo, description, private: isPrivate } = body;
  if (!token || !repo) {
    return NextResponse.json(
      { error: "GitHub token dan nama repo wajib diisi." },
      { status: 400 },
    );
  }

  const userRes = await githubFetch("https://api.github.com/user", token);
  if (!userRes.ok) {
    const detail = userRes.data?.message
      ? ` (${userRes.data.message})`
      : "";
    return NextResponse.json(
      { error: `Token GitHub tidak valid.${detail}` },
      { status: 401 },
    );
  }
  const user = userRes.data;
  const login = user.login;

  // Check if repo already exists to give a better error
  const existingRes = await githubFetch(
    `https://api.github.com/repos/${login}/${repo}`,
    token,
  );
  if (existingRes.ok) {
    return NextResponse.json(
      { error: `Repo "${login}/${repo}" sudah ada. Pilih nama repo lain.` },
      { status: 409 },
    );
  }

  const createRes = await githubFetch("https://api.github.com/user/repos", token, "POST", {
    name: repo,
    description: description || `IdeForge plan: ${plan.structure?.appName || plan.ideaText}`,
    private: isPrivate ?? false,
    auto_init: false,
  });

  if (!createRes.ok) {
    const msg = createRes.data?.message || "Unknown error";
    const errs = createRes.data?.errors;
    const detail = Array.isArray(errs)
      ? errs.map((e: Record<string, string>) => e.message || JSON.stringify(e)).join("; ")
      : msg;
    return NextResponse.json(
      { error: `Gagal membuat repo: ${detail}` },
      { status: 500 },
    );
  }

  const files = generateProjectFiles(plan);
  const results: { path: string; status: string; error?: string }[] = [];

  for (const file of files) {
    const encoded = Buffer.from(file.content).toString("base64");
    const putRes = await githubFetch(
      `https://api.github.com/repos/${login}/${repo}/contents/${file.path}`,
      token,
      "PUT",
      {
        message: `Add ${file.path} via IdeForge`,
        content: encoded,
      },
    );
    if (putRes.ok) {
      results.push({ path: file.path, status: "created" });
    } else {
      results.push({
        path: file.path,
        status: "failed",
        error: putRes.data?.message || `HTTP ${putRes.status}`,
      });
    }
  }

  const repoUrl = `https://github.com/${login}/${repo}`;
  const hasFailures = results.some((r) => r.status === "failed");

  return NextResponse.json({
    success: !hasFailures,
    repo: repoUrl,
    files: results,
  });
}
